### ISSUE TITLE
Still cannot Ward Reek

### ISSUE THREAD

**Issue by tfneptune** [throneteki/throneteki#3162]
Just tried to Ward pack my own Reek, still does not show up as a valid target. I do not see a reason why it fails to show up as a valid target.

**Comment by HannoDiomedes** [comment]
I think ironthrone treats Reek as non-unique. Should be fixed soon.

**Comment by tfneptune** [comment]
Awesome, sounds good. Thanks for letting me know.

**Comment by stopfstedt** [comment]
refs https://github.com/throneteki/throneteki-json-data/pull/109

**Comment by EvadLhorg** [comment]
Should be fixed now, json-data update deployed. can be closed

**Comment by RetroGeet** [comment]
Reek still appears to be functioning as "non-unique" - noticed this in multiple games today and yesterday. Both when trying to play a duplicate on him, playing "I am no one" on him and trying to attach "Ser Pounce" to him.

**Comment by stopfstedt** [comment]
confirmed.

![image](https://user-images.githubusercontent.com/1410427/126725027-6571e054-3879-49af-9b1b-7a4396bbee48.png)


this update never went out, @EvadLhorg

**Comment by EvadLhorg** [comment]
interesting, will see what went wrong. sorry about the inconvenience!

**Comment by EvadLhorg** [comment]
Should now finally be fixed :D
